#!/usr/bin/sh

sxhkd & 
polybar & 
picom &
xsetroot -cursor_name left_ptr

feh --bg-fill /home/tomasferreira/Pictures/Wallpapers/bf82f6956a32819af48c2572243e8286.jpg

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspwm border color#
bspc config focused_border_color	"#59C4F6"
bspc config normal_border_color		"#1F86B6"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
